// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type User struct {
	Username            string         `json:"username"`
	Email               string         `json:"email"`
	ScrobblingEnabled   bool           `json:"scrobbling_enabled"`
	AdminRole           bool           `json:"admin_role"`
	SettingsRole        bool           `json:"settings_role"`
	DownloadRole        bool           `json:"download_role"`
	UploadRole          bool           `json:"upload_role"`
	PlaylistRole        bool           `json:"playlist_role"`
	CoverArtRole        bool           `json:"cover_art_role"`
	CommentRole         bool           `json:"comment_role"`
	PodcastRole         bool           `json:"podcast_role"`
	StreamRole          bool           `json:"stream_role"`
	JukeboxRole         bool           `json:"jukebox_role"`
	ShareRole           bool           `json:"share_role"`
	VideoConversionRole bool           `json:"video_conversion_role"`
	AvatarLastChanged   sql.NullString `json:"avatar_last_changed"`
	Folder              sql.NullString `json:"folder"`
	MaxBitRate          sql.NullInt64  `json:"max_bit_rate"`
}
