// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT DISTINCT username, email, scrobbling_enabled, admin_role, settings_role, download_role, upload_role, playlist_role, cover_art_role, comment_role, podcast_role, stream_role, jukebox_role, share_role, video_conversion_role, avatar_last_changed, folder, max_bit_rate FROM users
WHERE username = ?
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.ScrobblingEnabled,
		&i.AdminRole,
		&i.SettingsRole,
		&i.DownloadRole,
		&i.UploadRole,
		&i.PlaylistRole,
		&i.CoverArtRole,
		&i.CommentRole,
		&i.PodcastRole,
		&i.StreamRole,
		&i.JukeboxRole,
		&i.ShareRole,
		&i.VideoConversionRole,
		&i.AvatarLastChanged,
		&i.Folder,
		&i.MaxBitRate,
	)
	return i, err
}
