version: "2"
linters:
  default: all
  disable:
    - wsl
    - gomodguard
    - depguard
    - testpackage
    - revive
    - godox
    - noinlineerr
    - errchkjson
    - tagliatelle
  settings:
    exhaustruct:
      include:
        - '^github\.com/Simon-Weij/allium(/.*)?\..+$'
    errcheck:
      exclude-functions:
        - (io.Closer).Close
    copyloopvar:
      check-alias: true
    decorder:
      disable-dec-order-check: false
    gosec:
      excludes:
        - G401
        - G501
        - G304
        - G703
        - G705
    varnamelen:
      ignore-decls:
        - w http.ResponseWriter
        - r *http.Request
      ignore-names:
        - id
    funlen:
      lines: 80
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - funlen
          - varnamelen
          - noctx
          - gosec
          - wrapcheck
