version: "2"
linters:
  enable:
    - exhaustruct
  settings:
    exhaustruct:
      include:
        - '^github\.com/Simon-Weij/allium(/.*)?\..+$'
    errcheck:
      exclude-functions:
        - (io.Closer).Close
