version: "2"
linters:
  default: standard
  enable:
    - gosec
    - wsl_v5
    - gocritic
    - varnamelen
    - prealloc
    - cyclop
    - gocognit
    - nestif
    - misspell
    - unconvert
    - unparam
    - wrapcheck
    - nilnil
    - nilnesserr
    - errorlint
    - mnd
    - modernize
    - decorder
    - funcorder
    - sloglint
    - errname
    - testifylint
    - paralleltest
    - thelper
  settings:
    gosec:
      excludes:
        - G104
        - G304
        - G401
        - G501
        - G703
        - G705
    varnamelen:
      ignore-names:
        - w
        - r
        - db
        - id
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - varnamelen
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Close` is not checked"
