services:
  app:
    build: .
    pull_policy: build
    ports:
      - "8080:8080"
    environment:
      ALLIUM_USERNAME: ${ALLIUM_USERNAME:-alice}
      ALLIUM_PASSWORD: ${ALLIUM_PASSWORD:-changeme}
    volumes:
      - data:/data
    develop:
      watch:
        - action: rebuild
          path: .
volumes:
  data:
